### ISSUE TITLE
EBS Snapshot ID

### ISSUE THREAD

**Issue by tudormunteanu** [kvnn/OrdServer#2]
hello @kvnn,

Thanks for setting this up. Is the EBS snapshot public? TF throws an error saying it can't find the ID you added as default to the variable.

**Comment by kvnn** [comment]
@tudormunteanu Sorry about that. I've just pushed the updated snapshot id (from yesterday).

**Comment by tudormunteanu** [comment]
@kvnn unsure it works as expected. Still throws:

> Error: Error creating EC2 volume: InvalidSnapshot.NotFound: Snapshot does not exist 

for `snap-0cf743ff2aa517142` . Is the snapshot public?

**Comment by kvnn** [comment]
@tudormunteanu It was not public ! Updated just now.

**Comment by tudormunteanu** [comment]
@kvnn , it worked. Thank you 🙏
